api_platform:
    title: 'API Usine Dev'
    description: 'Gestion des données organisationnelle, du personnel au services en passant par les plannings'
    version: '3.0.2'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json:
            mime_types: ['application/json']
            
        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']
    defaults:
        pagination_client_enabled: true
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default value
